server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3307/test?useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

  application:
    name: userservice

  cloud:
    nacos:
      server-addr: localhost:8848/nacos

mybatis:
  type-aliases-package: cn.itcast.user.pojo
  configuration:
    map-underscore-to-camel-case: true


#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka/
